[build]
builder = "nixpacks"

[deploy]
startCommand = "bash entrypoint.sh"
healthcheckPath = "/_health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[nixpacks]
start = "bash entrypoint.sh"
