[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0"
healthcheckPath = "/_health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[nixpacks]
start = "python -m uvicorn main:app --host 0.0.0.0"
