[build]
builder = "nixpacks"

[deploy]
startCommand = "python minimal_server.py"
healthcheckPath = "/_health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
healthcheckPort = 8000

[nixpacks]
start = "python minimal_server.py"
